version: '3.1'
services:
    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017
        networks:
          - bridge
        # command: mongod --bind_ip mongodb
    server:
        image: store_servide
        restart: always
        ports:
          - 8080:8080
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
        networks:
          - bridge
        depends_on:
          - mongo
networks:
  bridge:
    driver: bridge